name: Landfall
description: Focused release pipeline using semantic-release with optional LLM-powered synthesis.

inputs:
  github-token:
    description: Personal access token with repository write access.
    required: true
  llm-api-key:
    description: API key for LLM synthesis (OpenRouter, OpenAI, or any compatible provider).
    required: false
  llm-model:
    description: Primary model ID for synthesis (e.g., 'anthropic/claude-sonnet-4', 'openai/gpt-4o-mini').
    default: anthropic/claude-sonnet-4
    required: false
  llm-fallback-models:
    description: Comma-separated fallback model IDs tried in order if primary fails.
    default: "google/gemini-2.5-flash,openai/gpt-4o-mini"
    required: false
  llm-api-url:
    description: Chat completions endpoint URL (OpenAI-compatible).
    default: "https://openrouter.ai/api/v1/chat/completions"
    required: false
  node-version:
    description: Node.js version for semantic-release.
    default: "22"
    required: false
  synthesis:
    description: Whether to synthesize user-facing release notes.
    default: "true"
    required: false
  synthesis-required:
    description: Whether synthesis and release-body update failures should fail the action.
    default: "false"
    required: false
  synthesis-strict:
    description: Deprecated alias for synthesis-required.
    default: "false"
    required: false
  synthesis-failure-issue:
    description: Whether to create a GitHub issue in the consuming repository when synthesis fails.
    default: "true"
    required: false

outputs:
  released:
    description: Whether semantic-release published a release.
    value: ${{ steps.semantic_release.outputs.released }}
  release-tag:
    description: Release tag created by semantic-release.
    value: ${{ steps.semantic_release.outputs.release_tag }}
  synthesis-succeeded:
    description: Whether synthesis and release body update completed successfully.
    value: ${{ steps.synthesis_result.outputs.succeeded }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        set -euo pipefail
        npm install --no-fund --no-audit
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run semantic-release
      id: semantic_release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

        before_tags="$(mktemp)"
        after_tags="$(mktemp)"
        git tag | sort > "${before_tags}"

        npx --yes --prefix "${GITHUB_ACTION_PATH}" semantic-release \
          --extends "${GITHUB_ACTION_PATH}/configs/.releaserc.json"

        git tag | sort > "${after_tags}"
        new_tag="$(comm -13 "${before_tags}" "${after_tags}" | tail -n1 || true)"

        if [ -n "${new_tag}" ]; then
          echo "released=true" >> "${GITHUB_OUTPUT}"
          echo "release_tag=${new_tag}" >> "${GITHUB_OUTPUT}"
        else
          echo "released=false" >> "${GITHUB_OUTPUT}"
          echo "release_tag=" >> "${GITHUB_OUTPUT}"
        fi

    - name: Synthesize user-facing notes
      id: synthesize
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true'
      shell: bash
      run: |
        set -euo pipefail

        sanitize_text() {
          printf '%s' "$1" | tr '\r\n' ' ' | sed -E 's/[[:space:]]+/ /g' | sed -E 's/^ +| +$//g'
        }

        set_output() {
          local key="$1"
          local value="$2"
          printf '%s=%s\n' "${key}" "${value}" >> "${GITHUB_OUTPUT}"
        }

        notes_file="${RUNNER_TEMP}/landfall-whats-new.md"
        product_name="${GITHUB_REPOSITORY#*/}"
        api_key="${{ inputs.llm-api-key }}"

        set_output "succeeded" "false"
        set_output "notes_file" ""
        set_output "failure_stage" ""
        set_output "failure_message" ""

        if [ -z "${api_key}" ]; then
          message="Landfall synthesis skipped; llm-api-key is empty."
          echo "::warning::${message}"
          set_output "failure_stage" "configuration"
          set_output "failure_message" "$(sanitize_text "${message}")"
          exit 0
        fi

        synth_log="${RUNNER_TEMP}/landfall-synthesize.log"
        if ! python "${GITHUB_ACTION_PATH}/scripts/synthesize.py" \
          --api-key "${api_key}" \
          --model "${{ inputs.llm-model }}" \
          --api-url "${{ inputs.llm-api-url }}" \
          --fallback-models "${{ inputs.llm-fallback-models }}" \
          --product-name "${product_name}" \
          --version "${{ steps.semantic_release.outputs.release_tag }}" \
          --changelog-file "${GITHUB_WORKSPACE}/CHANGELOG.md" \
          --prompt-template "${GITHUB_ACTION_PATH}/templates/synthesis-prompt.md" \
          > "${notes_file}" \
          2> "${synth_log}"; then
          details="$(tail -n 5 "${synth_log}" | tr '\r\n' ' ' | sed -E 's/[[:space:]]+/ /g' | sed -E 's/^ +| +$//g')"
          message="Landfall synthesis failed; publishing release without a What's New section."
          if [ -n "${details}" ]; then
            message="${message} Details: ${details}"
          fi
          message="$(sanitize_text "${message}")"
          echo "::warning::${message}"
          set_output "failure_stage" "synthesis"
          set_output "failure_message" "${message}"
          exit 0
        fi

        if [ ! -s "${notes_file}" ]; then
          message="Landfall synthesis returned empty notes; skipping release update."
          echo "::warning::${message}"
          set_output "failure_stage" "synthesis_empty"
          set_output "failure_message" "$(sanitize_text "${message}")"
          exit 0
        fi

        set_output "succeeded" "true"
        set_output "notes_file" "${notes_file}"

    - name: Update release body
      id: update_release
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true'
      shell: bash
      env:
        SYNTH_STEP_SUCCEEDED: ${{ steps.synthesize.outputs.succeeded }}
        SYNTH_FAILURE_STAGE: ${{ steps.synthesize.outputs.failure_stage }}
        SYNTH_FAILURE_MESSAGE: ${{ steps.synthesize.outputs.failure_message }}
      run: |
        set -euo pipefail

        sanitize_text() {
          printf '%s' "$1" | tr '\r\n' ' ' | sed -E 's/[[:space:]]+/ /g' | sed -E 's/^ +| +$//g'
        }

        set_output() {
          local key="$1"
          local value="$2"
          printf '%s=%s\n' "${key}" "${value}" >> "${GITHUB_OUTPUT}"
        }

        set_output "succeeded" "false"
        set_output "failure_stage" ""
        set_output "failure_message" ""

        if [ "${SYNTH_STEP_SUCCEEDED}" != "true" ]; then
          stage="${SYNTH_FAILURE_STAGE}"
          message="${SYNTH_FAILURE_MESSAGE}"
          if [ -z "${stage}" ]; then
            stage="synthesis"
          fi
          if [ -z "${message}" ]; then
            message="Release body update skipped because synthesis did not succeed."
          fi
          set_output "failure_stage" "$(sanitize_text "${stage}")"
          set_output "failure_message" "$(sanitize_text "${message}")"
          exit 0
        fi

        update_log="${RUNNER_TEMP}/landfall-update-release.log"
        if ! python "${GITHUB_ACTION_PATH}/scripts/update-release.py" \
          --github-token "${{ inputs.github-token }}" \
          --repository "${GITHUB_REPOSITORY}" \
          --tag "${{ steps.semantic_release.outputs.release_tag }}" \
          --notes-file "${{ steps.synthesize.outputs.notes_file }}" \
          > /dev/null \
          2> "${update_log}"; then
          details="$(tail -n 5 "${update_log}" | tr '\r\n' ' ' | sed -E 's/[[:space:]]+/ /g' | sed -E 's/^ +| +$//g')"
          message="Landfall could not update the release body; release remains published."
          if [ -n "${details}" ]; then
            message="${message} Details: ${details}"
          fi
          message="$(sanitize_text "${message}")"
          echo "::warning::${message}"
          set_output "failure_stage" "release_update"
          set_output "failure_message" "${message}"
          exit 0
        fi

        set_output "succeeded" "true"

    - name: Summarize synthesis status
      id: synthesis_result
      shell: bash
      env:
        SYNTHESIS_ENABLED: ${{ inputs.synthesis }}
        RELEASED: ${{ steps.semantic_release.outputs.released }}
        SYNTH_STEP_SUCCEEDED: ${{ steps.synthesize.outputs.succeeded }}
        UPDATE_STEP_SUCCEEDED: ${{ steps.update_release.outputs.succeeded }}
        SYNTH_FAILURE_STAGE: ${{ steps.synthesize.outputs.failure_stage }}
        SYNTH_FAILURE_MESSAGE: ${{ steps.synthesize.outputs.failure_message }}
        UPDATE_FAILURE_STAGE: ${{ steps.update_release.outputs.failure_stage }}
        UPDATE_FAILURE_MESSAGE: ${{ steps.update_release.outputs.failure_message }}
      run: |
        set -euo pipefail

        set_output() {
          local key="$1"
          local value="$2"
          printf '%s=%s\n' "${key}" "${value}" >> "${GITHUB_OUTPUT}"
        }

        succeeded="false"
        failure_stage=""
        failure_message=""

        if [ "${SYNTHESIS_ENABLED}" = "true" ] && [ "${RELEASED}" = "true" ]; then
          if [ "${SYNTH_STEP_SUCCEEDED}" = "true" ] && [ "${UPDATE_STEP_SUCCEEDED}" = "true" ]; then
            succeeded="true"
          else
            failure_stage="${SYNTH_FAILURE_STAGE}"
            failure_message="${SYNTH_FAILURE_MESSAGE}"
            if [ -z "${failure_stage}" ] && [ -n "${UPDATE_FAILURE_STAGE}" ]; then
              failure_stage="${UPDATE_FAILURE_STAGE}"
              failure_message="${UPDATE_FAILURE_MESSAGE}"
            fi
            if [ -z "${failure_stage}" ]; then
              failure_stage="unknown"
            fi
            if [ -z "${failure_message}" ]; then
              failure_message="Landfall synthesis did not complete successfully."
            fi
          fi
        fi

        set_output "succeeded" "${succeeded}"
        set_output "failure_stage" "${failure_stage}"
        set_output "failure_message" "${failure_message}"

    - name: Report synthesis failure
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true' && inputs.synthesis-failure-issue == 'true' && steps.synthesis_result.outputs.succeeded != 'true'
      shell: bash
      env:
        FAILURE_STAGE: ${{ steps.synthesis_result.outputs.failure_stage }}
        FAILURE_MESSAGE: ${{ steps.synthesis_result.outputs.failure_message }}
      run: |
        set -euo pipefail
        run_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        if ! python "${GITHUB_ACTION_PATH}/scripts/report-synthesis-failure.py" \
          --github-token "${{ inputs.github-token }}" \
          --repository "${GITHUB_REPOSITORY}" \
          --release-tag "${{ steps.semantic_release.outputs.release_tag }}" \
          --workflow-run-url "${run_url}" \
          --workflow-name "${GITHUB_WORKFLOW}" \
          --failure-stage "${FAILURE_STAGE}" \
          --failure-message "${FAILURE_MESSAGE}"; then
          echo "::warning::Landfall could not create a synthesis failure issue."
        fi

    - name: Enforce synthesis required
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true'
      shell: bash
      env:
        SYNTHESIS_REQUIRED: ${{ inputs.synthesis-required }}
        SYNTHESIS_STRICT: ${{ inputs.synthesis-strict }}
        SYNTHESIS_SUCCEEDED: ${{ steps.synthesis_result.outputs.succeeded }}
        FAILURE_STAGE: ${{ steps.synthesis_result.outputs.failure_stage }}
        FAILURE_MESSAGE: ${{ steps.synthesis_result.outputs.failure_message }}
      run: |
        set -euo pipefail
        if [ "${SYNTHESIS_REQUIRED}" != "true" ] && [ "${SYNTHESIS_STRICT}" != "true" ]; then
          exit 0
        fi
        if [ "${SYNTHESIS_SUCCEEDED}" = "true" ]; then
          exit 0
        fi
        echo "::error::Landfall synthesis required but failed at stage '${FAILURE_STAGE}'. ${FAILURE_MESSAGE}"
        exit 1
