name: Landfall
description: Focused release pipeline using semantic-release with optional LLM-powered synthesis.

inputs:
  github-token:
    description: Personal access token with repository write access.
    required: true
  llm-api-key:
    description: API key for the LLM provider used for release-note synthesis.
    required: true
  llm-model:
    description: Model ID passed to the LLM provider.
    default: google/gemini-2.5-flash
    required: false
  llm-api-url:
    description: Chat-completions endpoint URL. Any OpenAI-compatible provider works.
    default: https://openrouter.ai/api/v1/chat/completions
    required: false
  # --- Deprecated aliases (backwards compatibility) ---
  moonshot-api-key:
    description: "[DEPRECATED — use llm-api-key] API key for Moonshot/Kimi synthesis."
    required: false
  moonshot-model:
    description: "[DEPRECATED — use llm-model] Moonshot model ID used for synthesis."
    required: false
  node-version:
    description: Node.js version for semantic-release.
    default: "22"
    required: false
  synthesis:
    description: Whether to synthesize user-facing release notes.
    default: "true"
    required: false

outputs:
  released:
    description: Whether semantic-release published a release.
    value: ${{ steps.semantic_release.outputs.released }}
  release-tag:
    description: Release tag created by semantic-release.
    value: ${{ steps.semantic_release.outputs.release_tag }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        set -euo pipefail
        npm install --no-fund --no-audit
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run semantic-release
      id: semantic_release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

        before_tags="$(mktemp)"
        after_tags="$(mktemp)"
        git tag | sort > "${before_tags}"

        npx --yes --prefix "${GITHUB_ACTION_PATH}" semantic-release \
          --extends "${GITHUB_ACTION_PATH}/configs/.releaserc.json"

        git tag | sort > "${after_tags}"
        new_tag="$(comm -13 "${before_tags}" "${after_tags}" | tail -n1 || true)"

        if [ -n "${new_tag}" ]; then
          echo "released=true" >> "${GITHUB_OUTPUT}"
          echo "release_tag=${new_tag}" >> "${GITHUB_OUTPUT}"
        else
          echo "released=false" >> "${GITHUB_OUTPUT}"
          echo "release_tag=" >> "${GITHUB_OUTPUT}"
        fi

    - name: Resolve LLM inputs
      id: llm
      shell: bash
      run: |
        set -euo pipefail
        # New inputs take precedence; fall back to deprecated moonshot-* aliases.
        api_key="${{ inputs.llm-api-key }}"
        [ -z "${api_key}" ] && api_key="${{ inputs.moonshot-api-key }}"

        model="${{ inputs.llm-model }}"
        if [ "${model}" = "google/gemini-2.5-flash" ] && [ -n "${{ inputs.moonshot-model }}" ]; then
          model="${{ inputs.moonshot-model }}"
        fi

        api_url="${{ inputs.llm-api-url }}"

        echo "api_key=${api_key}" >> "${GITHUB_OUTPUT}"
        echo "model=${model}" >> "${GITHUB_OUTPUT}"
        echo "api_url=${api_url}" >> "${GITHUB_OUTPUT}"

    - name: Synthesize user-facing notes
      id: synthesize
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true'
      shell: bash
      run: |
        set -euo pipefail
        notes_file="${RUNNER_TEMP}/landfall-whats-new.md"
        product_name="${GITHUB_REPOSITORY#*/}"
        if ! python "${GITHUB_ACTION_PATH}/scripts/synthesize.py" \
          --api-key "${{ steps.llm.outputs.api_key }}" \
          --model "${{ steps.llm.outputs.model }}" \
          --api-url "${{ steps.llm.outputs.api_url }}" \
          --product-name "${product_name}" \
          --version "${{ steps.semantic_release.outputs.release_tag }}" \
          --changelog-file "${GITHUB_WORKSPACE}/CHANGELOG.md" \
          --prompt-template "${GITHUB_ACTION_PATH}/templates/synthesis-prompt.md" \
          > "${notes_file}"; then
          echo "::warning::Landfall synthesis failed; publishing release without a What's New section."
          exit 0
        fi

        if [ ! -s "${notes_file}" ]; then
          echo "::warning::Landfall synthesis returned empty notes; skipping release update."
          exit 0
        fi

        echo "notes_file=${notes_file}" >> "${GITHUB_OUTPUT}"

    - name: Update release body
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true' && steps.synthesize.outputs.notes_file != ''
      shell: bash
      run: |
        set -euo pipefail
        if ! python "${GITHUB_ACTION_PATH}/scripts/update-release.py" \
          --github-token "${{ inputs.github-token }}" \
          --repository "${GITHUB_REPOSITORY}" \
          --tag "${{ steps.semantic_release.outputs.release_tag }}" \
          --notes-file "${{ steps.synthesize.outputs.notes_file }}"; then
          echo "::warning::Landfall could not update the release body; release remains published."
        fi
