name: Landfall
description: Focused release pipeline using semantic-release with optional LLM-powered synthesis.

inputs:
  github-token:
    description: Personal access token with repository write access.
    required: true
  llm-api-key:
    description: API key for LLM synthesis (OpenRouter, OpenAI, or any compatible provider).
    required: false
  llm-model:
    description: Primary model ID for synthesis (e.g., 'anthropic/claude-sonnet-4', 'openai/gpt-4o-mini').
    default: anthropic/claude-sonnet-4
    required: false
  llm-fallback-models:
    description: Comma-separated fallback model IDs tried in order if primary fails.
    default: "google/gemini-2.5-flash,openai/gpt-4o-mini"
    required: false
  llm-api-url:
    description: Chat completions endpoint URL (OpenAI-compatible).
    default: "https://openrouter.ai/api/v1/chat/completions"
    required: false
  node-version:
    description: Node.js version for semantic-release.
    default: "22"
    required: false
  synthesis:
    description: Whether to synthesize user-facing release notes.
    default: "true"
    required: false
  synthesis-strict:
    description: Whether synthesis and release-body update failures should fail the action.
    default: "false"
    required: false

outputs:
  released:
    description: Whether semantic-release published a release.
    value: ${{ steps.semantic_release.outputs.released }}
  release-tag:
    description: Release tag created by semantic-release.
    value: ${{ steps.semantic_release.outputs.release_tag }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        set -euo pipefail
        npm install --no-fund --no-audit
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Run semantic-release
      id: semantic_release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

        before_tags="$(mktemp)"
        after_tags="$(mktemp)"
        git tag | sort > "${before_tags}"

        npx --yes --prefix "${GITHUB_ACTION_PATH}" semantic-release \
          --extends "${GITHUB_ACTION_PATH}/configs/.releaserc.json"

        git tag | sort > "${after_tags}"
        new_tag="$(comm -13 "${before_tags}" "${after_tags}" | tail -n1 || true)"

        if [ -n "${new_tag}" ]; then
          echo "released=true" >> "${GITHUB_OUTPUT}"
          echo "release_tag=${new_tag}" >> "${GITHUB_OUTPUT}"
        else
          echo "released=false" >> "${GITHUB_OUTPUT}"
          echo "release_tag=" >> "${GITHUB_OUTPUT}"
        fi

    - name: Synthesize user-facing notes
      id: synthesize
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true'
      shell: bash
      run: |
        set -euo pipefail
        notes_file="${RUNNER_TEMP}/landfall-whats-new.md"
        product_name="${GITHUB_REPOSITORY#*/}"
        strict="${{ inputs.synthesis-strict }}"
        api_key="${{ inputs.llm-api-key }}"
        if [ -z "${api_key}" ]; then
          if [ "${strict}" = "true" ]; then
            echo "::error::Landfall synthesis required but llm-api-key is empty."
            exit 1
          fi
          echo "::warning::Landfall synthesis skipped; llm-api-key is empty."
          exit 0
        fi
        if ! python "${GITHUB_ACTION_PATH}/scripts/synthesize.py" \
          --api-key "${api_key}" \
          --model "${{ inputs.llm-model }}" \
          --api-url "${{ inputs.llm-api-url }}" \
          --fallback-models "${{ inputs.llm-fallback-models }}" \
          --product-name "${product_name}" \
          --version "${{ steps.semantic_release.outputs.release_tag }}" \
          --changelog-file "${GITHUB_WORKSPACE}/CHANGELOG.md" \
          --prompt-template "${GITHUB_ACTION_PATH}/templates/synthesis-prompt.md" \
          > "${notes_file}"; then
          if [ "${strict}" = "true" ]; then
            echo "::error::Landfall synthesis failed and synthesis-strict is enabled."
            exit 1
          fi
          echo "::warning::Landfall synthesis failed; publishing release without a What's New section."
          exit 0
        fi

        if [ ! -s "${notes_file}" ]; then
          if [ "${strict}" = "true" ]; then
            echo "::error::Landfall synthesis returned empty notes and synthesis-strict is enabled."
            exit 1
          fi
          echo "::warning::Landfall synthesis returned empty notes; skipping release update."
          exit 0
        fi

        echo "notes_file=${notes_file}" >> "${GITHUB_OUTPUT}"

    - name: Update release body
      if: inputs.synthesis == 'true' && steps.semantic_release.outputs.released == 'true' && steps.synthesize.outputs.notes_file != ''
      shell: bash
      run: |
        set -euo pipefail
        strict="${{ inputs.synthesis-strict }}"
        if ! python "${GITHUB_ACTION_PATH}/scripts/update-release.py" \
          --github-token "${{ inputs.github-token }}" \
          --repository "${GITHUB_REPOSITORY}" \
          --tag "${{ steps.semantic_release.outputs.release_tag }}" \
          --notes-file "${{ steps.synthesize.outputs.notes_file }}"; then
          if [ "${strict}" = "true" ]; then
            echo "::error::Landfall could not update the release body and synthesis-strict is enabled."
            exit 1
          fi
          echo "::warning::Landfall could not update the release body; release remains published."
        fi
